import {
    LayoutDashboard,
    Briefcase,
    Star,
    BarChart3,
    TrendingUp,
    Target,
    ArrowLeftRight,
    Bell,
    Settings,
} from "lucide-react";
import { ArrowDownLeft, ArrowUpRight } from "lucide-react";

export const NAV_ITEMS = [
    { label: "Dashboard", icon: LayoutDashboard, path: "/dashboard" },
    { label: "Portfolio", icon: Briefcase, path: "/portfolio" },
    { label: "Watchlist", icon: Star, path: "/watchlist" },
    { label: "Analytics", icon: BarChart3, path: "/analytics" },
    { label: "Market Overview", icon: TrendingUp, path: "/market-overview" },
    { label: "Goals", icon: Target, path: "/goals" },
    { label: "Transactions", icon: ArrowLeftRight, path: "/transactions" },
    { label: "Notifications", icon: Bell, path: "/notifications" },
    { label: "Settings", icon: Settings, path: "/settings" },
];

export const ASSET_TABS = ["All", "Equity", "Mutual Funds", "Crypto", "Cash"];
export const TYPE_FILTERS = ["All", "Buy", "Sell", "Deposit", "Withdrawal"];

export const INITIAL_TRANSACTIONS = [
    {
        id: 1,
        ticker: "AAPL",
        name: "Apple Inc.",
        initial: "AP",
        color: "#8c4a3a",
        assetClass: "Equity",
        type: "Buy",
        qty: 10,
        unitLabel: "Shares",
        amount: 21250,
        date: "2h ago",
        status: "Completed",
    },
    {
        id: 2,
        ticker: "RELIANCE",
        name: "Reliance Ind.",
        initial: "RE",
        color: "#3a4a8c",
        assetClass: "Equity",
        type: "Buy",
        qty: 5,
        unitLabel: "Shares",
        amount: 12890,
        date: "5h ago",
        status: "Completed",
    },
    {
        id: 3,
        ticker: "TCS",
        name: "Tata Consultancy",
        initial: "TC",
        color: "#1f5c4f",
        assetClass: "Equity",
        type: "Buy",
        qty: 8,
        unitLabel: "Shares",
        amount: 18190,
        date: "1d ago",
        status: "Completed",
    },
    {
        id: 4,
        ticker: "INFY",
        name: "Infosys Ltd.",
        initial: "IN",
        color: "#1565c0",
        assetClass: "Equity",
        type: "Sell",
        qty: 4,
        unitLabel: "Shares",
        amount: 6720,
        date: "2d ago",
        status: "Completed",
    },
    {
        id: 5,
        ticker: "HDFCBANK",
        name: "HDFC Bank",
        initial: "HD",
        color: "#8c1c1c",
        assetClass: "Equity",
        type: "Buy",
        qty: 6,
        unitLabel: "Shares",
        amount: 9000,
        date: "3d ago",
        status: "Pending",
    },
    {
        id: 6,
        ticker: "BTC",
        name: "Bitcoin",
        initial: "₿",
        color: "#a3650f",
        assetClass: "Crypto",
        type: "Buy",
        qty: 0.05,
        unitLabel: "BTC",
        amount: 215000,
        date: "3d ago",
        status: "Completed",
    },
    {
        id: 7,
        ticker: "ABCF",
        name: "Axis Bluechip Fund",
        initial: "AB",
        color: "#2f6b5e",
        assetClass: "Mutual Funds",
        type: "Buy",
        qty: 25,
        unitLabel: "Units",
        amount: 12500,
        date: "4d ago",
        status: "Completed",
    },
    {
        id: 8,
        ticker: "AAPL",
        name: "Apple Inc.",
        initial: "AP",
        color: "#8c4a3a",
        assetClass: "Equity",
        type: "Sell",
        qty: 2,
        unitLabel: "Shares",
        amount: 4250,
        date: "4d ago",
        status: "Completed",
    },
    {
        id: 9,
        ticker: "CASH",
        name: "Wallet Top-up",
        initial: "₹",
        color: "#3a3a4a",
        assetClass: "Cash",
        type: "Deposit",
        qty: null,
        unitLabel: "",
        amount: 5000,
        date: "6d ago",
        status: "Completed",
    },
    {
        id: 10,
        ticker: "CASH",
        name: "Wallet Withdrawal",
        initial: "₹",
        color: "#3a3a4a",
        assetClass: "Cash",
        type: "Withdrawal",
        qty: null,
        unitLabel: "",
        amount: 2000,
        date: "1w ago",
        status: "Completed",
    },
];

export const inr = (n) => `₹${Math.round(n).toLocaleString("en-IN")}`;

export const TYPE_STYLES = {
    Buy: {
        color: "text-emerald-400",
        bg: "bg-emerald-500/10",
        icon: ArrowDownLeft,
    },
    Sell: { color: "text-rose-400", bg: "bg-rose-500/10", icon: ArrowUpRight },
    Deposit: {
        color: "text-blue-400",
        bg: "bg-blue-500/10",
        icon: ArrowDownLeft,
    },
    Withdrawal: {
        color: "text-amber-400",
        bg: "bg-amber-500/10",
        icon: ArrowUpRight,
    },
};

export const emptyForm = {
    name: "",
    ticker: "",
    assetClass: "Equity",
    type: "Buy",
    qty: "",
    amount: "",
};